import {
  Heading1,
  Heading2,
  Heading3,
  Bold,
  Italic,
  List,
  ListOrdered,
  ListTodo,
  ListChecks,
  Quote,
  FileCode,
  Table as TableIcon,
  Link2,
  ImageIcon,
  CalendarDays,
  Clock3,
  Minus,
} from "lucide-react";
import type { SlashCommand } from "./types";

export const SLASH_COMMANDS: SlashCommand[] = [
  { id: "h1", label: "Heading 1", keywords: ["title", "#"], icon: <Heading1 className="h-4 w-4" />, action: (s) => s.handleFormat("line", "# ") },
  { id: "h2", label: "Heading 2", keywords: ["subtitle", "##"], icon: <Heading2 className="h-4 w-4" />, action: (s) => s.handleFormat("line", "## ") },
  { id: "h3", label: "Heading 3", keywords: ["section", "###"], icon: <Heading3 className="h-4 w-4" />, action: (s) => s.handleFormat("line", "### ") },
  { id: "bold", label: "Bold", keywords: ["strong"], icon: <Bold className="h-4 w-4" />, action: (s) => s.handleFormat("wrap", "**", "**") },
  { id: "italic", label: "Italic", keywords: ["emphasis"], icon: <Italic className="h-4 w-4" />, action: (s) => s.handleFormat("wrap", "*", "*") },
  { id: "list", label: "Bullet List", keywords: ["unordered"], icon: <List className="h-4 w-4" />, action: (s) => s.handleFormat("line", "- ") },
  { id: "numlist", label: "Numbered List", keywords: ["ordered"], icon: <ListOrdered className="h-4 w-4" />, action: (s) => s.handleFormat("line", "1. ") },
  { id: "todo", label: "Todo List", keywords: ["task", "checkbox"], icon: <ListTodo className="h-4 w-4" />, action: (s) => s.handleFormat("line", "- [ ] ") },
  { id: "done", label: "Done List", keywords: ["task done", "check"], icon: <ListChecks className="h-4 w-4" />, action: (s) => s.handleFormat("line", "- [x] ") },
  { id: "quote", label: "Quote", keywords: ["blockquote"], icon: <Quote className="h-4 w-4" />, action: (s) => s.handleFormat("line", "> ") },
  { id: "code", label: "Code Block", keywords: ["snippet"], icon: <FileCode className="h-4 w-4" />, action: (s) => s.handleFormat("wrap", "```\n", "\n```") },
  { id: "table", label: "Table", keywords: ["grid"], icon: <TableIcon className="h-4 w-4" />, action: (s) => s.handleInsertTable() },
  { id: "link", label: "Link", keywords: ["url"], icon: <Link2 className="h-4 w-4" />, action: (s) => s.insertTextAtCursor("[title](https://)") },
  { id: "image", label: "Image", keywords: ["media"], icon: <ImageIcon className="h-4 w-4" />, action: (s) => s.insertTextAtCursor("![alt](https://)") },
  { id: "callout", label: "Callout", keywords: ["note", "tip", "warning"], icon: <ListChecks className="h-4 w-4" />, action: (s) => s.insertTextAtCursor(":::info\nNote\n:::\n") },
  { id: "date", label: "Current Date", keywords: ["today", "time"], icon: <CalendarDays className="h-4 w-4" />, action: (s) => s.insertTextAtCursor(new Date().toISOString().slice(0, 10)) },
  { id: "time", label: "Current Time", keywords: ["clock"], icon: <Clock3 className="h-4 w-4" />, action: (s) => s.insertTextAtCursor(new Date().toLocaleTimeString("en-US", { hour12: false })) },
  { id: "divider", label: "Divider", keywords: ["hr", "line"], icon: <Minus className="h-4 w-4" />, action: (s) => s.insertTextAtCursor("\n---\n") },
];
